### ISSUE TITLE
GPU && OpenCV = 1

### ISSUE THREAD

**Issue by vfbsilva** [daisukekobayashi/darknet-docker#2]
Would it be possible to have a script building for this combination of flags?

**Comment by daisukekobayashi** [comment]
Yes. Could you try to execute the script as written below.

```sh
#!/bin/bash

SOURCE_BRANCH="master"
SOURCE_COMMIT=`git ls-remote https://github.com/AlexeyAB/darknet.git HEAD | awk '{ print $1 }'`
VAR="gpu-cv"

docker build \
  --build-arg CONFIG=$VAR \
  --build-arg ADDITIONAL_PACKAGES="libopencv-dev" \
  --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  -t darknet .
```

I have dockerhub repository and set to build automatically.
So if you prefer prebuilt docker image, please execute command below.

```
docker pull daisukekobayashi/darknet:gpu-cv
```

https://hub.docker.com/repository/docker/daisukekobayashi/darknet

**Comment by vfbsilva** [comment]
@daisukekobayashi  I did find the docker hub later and your suggested flag does work as intended. Thanks a lot.
