### ISSUE TITLE
is cuda toolkit a necessity for running darknet?

### ISSUE THREAD

**Issue by IbrahimBond** [daisukekobayashi/darknet-docker#5]
i am trying to run darknet inside cuda docker container. my issue is that the cuda-devel base image which include the cuda toolkit has a size of over 3gb. i want to use the absolute bare minimum of cuda functionality in my docker image for running darknet in order to reduce docker image size.

any insight regarding this is appreciated.

**Comment by daisukekobayashi** [comment]
I think cuda-devel image is only needed for building darknet and
darknet only use cuda-runtime on runtime.
So after building darknet, we can switch cuda-devel to cuda-runtime and reduce image  size (removing devel pacakges and install runtime packages).
It needs time to check, so I haven’t tried it so far. But I think we can do it theoretically.

**Comment by daisukekobayashi** [comment]
I'm sorry it was my misunderstanding.
Once a file is in a layer it can't be removed. You can use multi stage builds to reduce docker image size.

**Comment by IbrahimBond** [comment]
i see, i guess i need to find time to test it. i will post an update once i try it. 
i am also aware of the layers concept, and that i need to use multistage builds. nontheless thanks for the headsup

**Comment by IbrahimBond** [comment]
i have tried the theory outside docker containers, and it proved to be correct. i have removed the cuda toolkit path from the bashrc file and darknet could detect objects perfectly fine.
